on:
  push:
    branches:
    - master

jobs:
  build:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    permissions:
      contents: read
      pages: write
      id-token: write
    name: deploy to github pages
    runs-on: ubuntu-latest
    steps:
    - name: Configure GitHub Pages
      uses: actions/configure-pages@v5.0.0

    - name: Checkout
      uses: actions/checkout@v4.2.2
    
    - name: Setup Node
      uses: actions/setup-node@v3.9.1
      with:
        node-version: '20.x'

    - name: Install Dependencies
      run: npm install

    - name: Vite Build
      run: npm run build

    - name: Manual move the index
      run: mv dist/index.html dist/corruskivi/index.html

    - name: Manual copy the index
      run: cp dist/corruskivi/index.html dist/corruskivi/preview.html

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist/corruskivi'

    - name: Pages Deploy
      id: deployment
      uses: actions/deploy-pages@v4
        
      
          
